### ISSUE TITLE
Hey cmehay, Permission pour Utiliser ton Design de Radio 42 pour un Plugin ?

### ISSUE THREAD

**Issue by tlloancy** [cmehay/radio_42#2]
Salut cmehay,

Ça fait un bail, presque 10 ans si je ne me trompe pas ! J'espère que tu vas bien. Je me souviens encore de notre échange sur radio 42, et franchement, ton projet m'a toujours inspiré.

Je travaille sur un plugin sur Wordpress que j'appelle "Simple Radio Forty Two". L'idée est de partir de ton design de base mais en permettant aux utilisateurs de personnaliser l'apparence comme ils le veulent. 

Tu serais d'accord pour que j'utilise ton design de base pour ce projet ? Je veux m'assurer de bien créditer ton travail original et si tu as des conditions ou des idées à ajouter, je suis tout ouïe.

Merci d'avance et à bientôt j'espère,

tlloancy

**Comment by cmehay** [comment]
Hello,

Pas de soucis pour moi. Pas nécessaire de me créditer.

À bientôt

**Comment by tlloancy** [comment]
Merci !

**Comment by tlloancy** [comment]
La première version de "Simple Radio Forty Two" est prête à être uploadée ! Je suis en train de finaliser les détails avant de la soumettre à WordPress.org. 

Je te remercie encore une fois pour ton inspiration et ton encouragement. Je te tiendrai au courant une fois que le plugin sera live ou si tu as des idées ou des retours, n'hésite pas à me les faire savoir.

Merci beaucoup pour tout !
